### ISSUE TITLE
ui_install generated an error

### ISSUE THREAD

**Issue by vmcilwain** [vmcilwain/myrails#1]
$ myrails ui_install
      create  app/controllers/ui_controller.rb
      create  app/views/ui/index.html.haml
/Users/lovell.m/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions.rb:90:in `action': wrong number of arguments (given 0, expected 1) (ArgumentError)
        from /Users/lovell.m/.rvm/gems/ruby-2.3.0/gems/myrails-1.0.0/lib/myrails.rb:65:in`block in ui_install'
        from /Users/lovell.m/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:46:in `initialize'
        from /Users/lovell.m/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:30:in`new'
        from /Users/lovell.m/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:30:in `insert_into_file'
        from /Users/lovell.m/.rvm/gems/ruby-2.3.0/gems/myrails-1.0.0/lib/myrails.rb:61:in`ui_install'
        from /Users/lovell.m/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/lovell.m/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'

```
    from /Users/lovell.m/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/lovell.m/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/lovell.m/.rvm/gems/ruby-2.3.0/gems/myrails-1.0.0/lib/myrails.rb:399:in `<top (required)>'
    from /Users/lovell.m/.rvm/gems/ruby-2.3.0/gems/myrails-1.0.0/bin/myrails:3:in `require_relative'
    from /Users/lovell.m/.rvm/gems/ruby-2.3.0/gems/myrails-1.0.0/bin/myrails:3:in `<top (required)>'
    from /Users/lovell.m/.rvm/gems/ruby-2.3.0/bin/myrails:23:in `load'
    from /Users/lovell.m/.rvm/gems/ruby-2.3.0/bin/myrails:23:in `<main>'
    from /Users/lovell.m/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/lovell.m/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by vmcilwain** [comment]
This is an issue with Thor not being compatible with ruby 2.3. Will investigate at a later time on how to deal with that.

**Comment by vmcilwain** [comment]
another related to ruby 2.3.0

/home/ubuntu/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x922354
 thor-0.19.1> (NoMethodError)
        from /home/ubuntu/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
        from /home/ubuntu/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
        from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/myrails-1.0.3/lib/myrails.rb:2:in `<top (required)>'

        from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/myrails-1.0.3/bin/myrails:3:in `require_relative'
        from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/myrails-1.0.3/bin/myrails:3:in `<top (required)>'
        from /home/ubuntu/.rvm/gems/ruby-2.3.0/bin/myrails:23:in `load'
        from /home/ubuntu/.rvm/gems/ruby-2.3.0/bin/myrails:23:in `<main>'
        from /home/ubuntu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/ubuntu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by vmcilwain** [comment]
Have not seen this for a while so I am closing it.
